#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1/

traits:
  - securedBySteroidsApiKey:
      headers:
        steroidsApiKey:
          type: string
          example: exampleapikey
          default: d44d109550c8f4b53e2cba979bf93299484cfeb02aa955cc0d87aaf2c191028a
        steroidsAppId:
          type: integer
          example: 1234
          default: 42124

schemas:
  - Workout_collection: '{"$schema":"http://json-schema.org/schema","title":"Workout collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Workout representation","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"title":{"type":"string"},"exercise":{"type":"array"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"_version":{"type":"integer"},"ACL":{"type":"object"}},"required":[]}}}}'
  - Workout_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Workout representation","properties":{"object":{"type":"object","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"title":{"type":"string"},"exercise":{"type":"array"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"_version":{"type":"integer"},"ACL":{"type":"object"}},"required":[]}}}'
  - Day_collection: '{"$schema":"http://json-schema.org/schema","title":"Day collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Day representation","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"day":{"type":"string"},"workout":{"type":"array"},"ACL":{"type":"object"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"_version":{"type":"integer"}},"required":[]}}}}'
  - Day_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Day representation","properties":{"object":{"type":"object","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"day":{"type":"string"},"workout":{"type":"array"},"ACL":{"type":"object"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"_version":{"type":"integer"}},"required":[]}}}'
  - Exercise_collection: '{"$schema":"http://json-schema.org/schema","title":"Exercise collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Exercise representation","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"name":{"type":"string"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"ACL":{"type":"object"},"__loc":{"type":"string"},"reps":{"type":"string"},"repgoal":{"type":"string"},"rephistory":{"type":"array"},"_version":{"type":"integer"}},"required":[]}}}}'
  - Exercise_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Exercise representation","properties":{"object":{"type":"object","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"name":{"type":"string"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"ACL":{"type":"object"},"__loc":{"type":"string"},"reps":{"type":"string"},"repgoal":{"type":"string"},"rephistory":{"type":"array"},"_version":{"type":"integer"}},"required":[]}}}'
  - Log_collection: '{"$schema":"http://json-schema.org/schema","title":"Log collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Log representation","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"workout":{"type":"array"},"date":{"type":"string"},"ACL":{"type":"object"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"_version":{"type":"integer"}},"required":[]}}}}'
  - Log_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical Log representation","properties":{"object":{"type":"object","properties":{"updated_at":{"type":"string"},"created_at":{"type":"string"},"workout":{"type":"array"},"date":{"type":"string"},"ACL":{"type":"object"},"tags":{"type":"array"},"updated_by":{"type":"string"},"created_by":{"type":"string"},"app_user_object_uid":{"type":"string"},"published":{"type":"boolean"},"uid":{"type":"string"},"_version":{"type":"integer"}},"required":[]}}}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:

  - built_io_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - built_io_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/Workout:
  description: |
    {
      "resourceName": "Workout",
      "identifierKey": "uid"
    }
  type: built_io_collection
  /{id}:
    type: built_io_member

/Day:
  description: |
    {
      "resourceName": "Day",
      "identifierKey": "uid"
    }
  type: built_io_collection
  /{id}:
    type: built_io_member

/Exercise:
  description: |
    {
      "resourceName": "Exercise",
      "identifierKey": "uid"
    }
  type: built_io_collection
  /{id}:
    type: built_io_member

/Log:
  description: |
    {
      "resourceName": "Log",
      "identifierKey": "uid"
    }
  type: built_io_collection
  /{id}:
    type: built_io_member


